# docker compose up -d to turn on the service in daemon mode
# docker compose down
# Visit container: localhost:46080. I'm already in linux, how do I do this? There's vnc.
version: '3.4'
services:
  sad-workspace:  # single docker 
    environment:
      - VNC_PW=abc123
      - VNC_GEOMETRY=1920x1080
      - VNC_DEPTH=24
    build:
      context: .
    image: deep-blue-slam-rico
    volumes:
      - /home/${USER}/file_exchange_port/Deep-Blue-Academy-SLAM/:/home/rico/
    ports:
      - 46080:6080
      - 45901:5901
